version: "3.8"

services:
  app:
    image: martincarrion01/informesfincas:1
    ports: 
      - "3001:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    command: ["./wait-for-it.sh", "db:3306", "--timeout=1000", "--", "node", "dist/index.js"]
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=informesfincas
      - MYSQL_ROOT_PASSWORD=password
    ports: 
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    ports: 
      - "6379:6379"

volumes:
  db: